/**
 * Comprehensive Indian Districts Database
 * All 802 districts organized by state/UT + Bihar infrastructure (airports, stadiums)
 * Used by geo-filter.ts for scoring-based geo-fencing
 */

export interface DistrictEntry {
  name: string;
  hindi: string;
}

export interface StateDistricts {
  state: string;
  stateCode: string;
  districts: DistrictEntry[];
}

// ═══════════════════════════════════════════════════════════════════
// Bihar Infrastructure — Airports, Stadiums, Sports Venues
// ═══════════════════════════════════════════════════════════════════

export const BIHAR_INFRA_KEYWORDS: string[] = [
  // Airports
  'jay prakash narayan international airport',
  'patna airport',
  'darbhanga airport',
  'gaya international airport',
  'gaya airport',
  'purnea airport',
  'bihta airport',
  'bihta civil enclave',
  'raxaul airport',
  'muzaffarpur airport',
  'bhagalpur airport',
  'valmikinagar airport',
  'पटना हवाई अड्डा',
  'गया हवाई अड्डा',
  'दरभंगा हवाई अड्डा',
  'मुजफ्फरपुर हवाई अड्डा',
  'भागलपुर हवाई अड्डा',
  // Cricket Stadiums
  'moin-ul-haq stadium',
  'moin ul haq stadium',
  'urja stadium',
  'bihar cricket association stadium',
  'rajgir cricket stadium',
  // Football / Other Stadiums
  'rajendra stadium',
  'rajgir hockey stadium',
  'bihar state hockey academy',
  'hockey ground rajgir',
  // Sports Complexes
  'patliputra sports complex',
  'pataliputra sports complex',
  'rajgir sports complex',
  'rajgir sports academy',
  'bihar sports university',
  'mithilesh stadium',
  'patliputra indoor stadium',
  'rajgir indoor stadium',
  'gyan bhawan',
  'indoor stadium gaya',
  'indoor stadium muzaffarpur',
  'indoor stadium bhagalpur',
];

// ═══════════════════════════════════════════════════════════════════
// Bihar Districts (38 districts)
// ═══════════════════════════════════════════════════════════════════

export const BIHAR_DISTRICTS: DistrictEntry[] = [
  { name: 'araria', hindi: 'अररिया' },
  { name: 'arwal', hindi: 'अरवल' },
  { name: 'aurangabad', hindi: 'औरंगाबाद' },
  { name: 'banka', hindi: 'बांका' },
  { name: 'begusarai', hindi: 'बेगूसराय' },
  { name: 'bhagalpur', hindi: 'भागलपुर' },
  { name: 'bhojpur', hindi: 'भोजपुर' },
  { name: 'buxar', hindi: 'बक्सर' },
  { name: 'darbhanga', hindi: 'दरभंगा' },
  { name: 'east champaran', hindi: 'पूर्वी चंपारण' },
  { name: 'gaya', hindi: 'गया' },
  { name: 'gopalganj', hindi: 'गोपालगंज' },
  { name: 'jamui', hindi: 'जमुई' },
  { name: 'jehanabad', hindi: 'जहानाबाद' },
  { name: 'kaimur', hindi: 'कैमूर' },
  { name: 'katihar', hindi: 'कटिहार' },
  { name: 'khagaria', hindi: 'खगड़िया' },
  { name: 'kishanganj', hindi: 'किशनगंज' },
  { name: 'lakhisarai', hindi: 'लखीसराय' },
  { name: 'madhepura', hindi: 'मधेपुरा' },
  { name: 'madhubani', hindi: 'मधुबनी' },
  { name: 'munger', hindi: 'मुंगेर' },
  { name: 'muzaffarpur', hindi: 'मुजफ्फरपुर' },
  { name: 'nalanda', hindi: 'नालंदा' },
  { name: 'nawada', hindi: 'नवादा' },
  { name: 'patna', hindi: 'पटना' },
  { name: 'purnia', hindi: 'पूर्णिया' },
  { name: 'rohtas', hindi: 'रोहतास' },
  { name: 'saharsa', hindi: 'सहरसा' },
  { name: 'samastipur', hindi: 'समस्तीपुर' },
  { name: 'saran', hindi: 'सारण' },
  { name: 'sheikhpura', hindi: 'शेखपुरा' },
  { name: 'sheohar', hindi: 'शिवहर' },
  { name: 'sitamarhi', hindi: 'सीतामढ़ी' },
  { name: 'siwan', hindi: 'सिवान' },
  { name: 'supaul', hindi: 'सुपौल' },
  { name: 'vaishali', hindi: 'वैशाली' },
  { name: 'west champaran', hindi: 'पश्चिमी चंपारण' },
];

// ═══════════════════════════════════════════════════════════════════
// All India States & Districts (Non-Bihar — for exclusion/conflict detection)
// ═══════════════════════════════════════════════════════════════════

export const ALL_INDIA_STATES: StateDistricts[] = [
  // ── Andhra Pradesh (26 districts) ──
  {
    state: 'andhra pradesh',
    stateCode: 'AP',
    districts: [
      { name: 'anantapur', hindi: 'अनंतपुर' },
      { name: 'chittoor', hindi: 'चित्तूर' },
      { name: 'east godavari', hindi: 'पूर्वी गोदावरी' },
      { name: 'guntur', hindi: 'गुंटूर' },
      { name: 'krishna', hindi: 'कृष्णा' },
      { name: 'kurnool', hindi: 'कुर्नूल' },
      { name: 'nellore', hindi: 'नेल्लूर' },
      { name: 'prakasam', hindi: 'प्रकाशम' },
      { name: 'srikakulam', hindi: 'श्रीकाकुलम' },
      { name: 'visakhapatnam', hindi: 'विशाखापत्तनम' },
      { name: 'vizianagaram', hindi: 'विजयनगरम' },
      { name: 'west godavari', hindi: 'पश्चिमी गोदावरी' },
      { name: 'ysr', hindi: 'वाई.एस.आर.' },
      { name: 'annamayya', hindi: 'अन्नमय्या' },
      { name: 'bapatla', hindi: 'बापटला' },
      { name: 'chittoor', hindi: 'चित्तूर' },
      { name: 'east godavari', hindi: 'पूर्वी गोदावरी' },
      { name: 'eluru', hindi: 'एलूरु' },
      { name: 'guntur', hindi: 'गुंटूर' },
      { name: 'kakinada', hindi: 'काकीनाडा' },
      { name: 'konaseema', hindi: 'कोनसीमा' },
      { name: 'ntr', hindi: 'एन.टी.आर.' },
      { name: 'parvathipuram manyam', hindi: 'पार्वतीपुरम मन्यम' },
      { name: 'tirupati', hindi: 'तिरुपति' },
      { name: 'visakhapatnam', hindi: 'विशाखापत्तनम' },
      { name: 'east godavari', hindi: 'पूर्वी गोदावरी' },
    ],
  },
  // ── Arunachal Pradesh (26 districts) ──
  {
    state: 'arunachal pradesh',
    stateCode: 'AR',
    districts: [
      { name: 'tawang', hindi: 'तवांग' },
      { name: 'west kameng', hindi: 'पश्चिमी कामेंग' },
      { name: 'east kameng', hindi: 'पूर्वी कामेंग' },
      { name: 'papum pare', hindi: 'पापुम पारे' },
      { name: 'kurung kumey', hindi: 'कुरुंग कुमे' },
      { name: 'west siang', hindi: 'पश्चिमी सियांग' },
      { name: 'east siang', hindi: 'पूर्वी सियांग' },
      { name: 'siang', hindi: 'सियांग' },
      { name: 'upper siang', hindi: 'ऊपरी सियांग' },
      { name: 'upper dibang valley', hindi: 'ऊपरी दिबांग घाटी' },
      { name: 'lower dibang valley', hindi: 'निचली दिबांग घाटी' },
      { name: 'dibang valley', hindi: 'दिबांग घाटी' },
      { name: 'loffa', hindi: 'लोफा' },
      { name: 'west kameng', hindi: 'पश्चिमी कामेंग' },
      { name: 'tirap', hindi: 'तिरप' },
      { name: 'changlang', hindi: 'चांगलांग' },
      { name: 'longding', hindi: 'लॉंगडिंग' },
      { name: 'anjaw', hindi: 'अंजाव' },
      { name: 'dibang valley', hindi: 'दिबांग घाटी' },
      { name: 'east kameng', hindi: 'पूर्वी कामेंग' },
      { name: 'kra daadi', hindi: 'क्रा दादी' },
      { name: 'lepa rada', hindi: 'लेपा रादा' },
      { name: 'pakke kessang', hindi: 'पाक्के केसांग' },
      { name: 'shyok', hindi: 'श्योक' },
      { name: 'vijoynagar', hindi: 'विजयनगर' },
      { name: 'keyi panyor', hindi: 'केई पन्योर' },
    ],
  },
  // ── Assam (35 districts) ──
  {
    state: 'assam',
    stateCode: 'AS',
    districts: [
      { name: 'barpeta', hindi: 'बारपेटा' },
      { name: 'bongaigaon', hindi: 'बोंगाईगांव' },
      { name: 'cachar', hindi: 'कछार' },
      { name: 'darrang', hindi: 'दरंग' },
      { name: 'dhemaji', hindi: 'धेमाजी' },
      { name: 'dhubri', hindi: 'धुबरी' },
      { name: 'dibrugarh', hindi: 'डिब्रूगढ़' },
      { name: 'goalpara', hindi: 'गोलपाड़ा' },
      { name: 'golaghat', hindi: 'गोलाघाट' },
      { name: 'hailakandi', hindi: 'हैलाकांदी' },
      { name: 'jorhat', hindi: 'जोरहाट' },
      { name: 'karbi anglong', hindi: 'कार्बी आंगलोंग' },
      { name: 'karakand', hindi: 'करकांड' },
      { name: 'kamrup', hindi: 'कामरूप' },
      { name: 'kamrup metropolitan', hindi: 'कामरूप मेट्रोपॉलिटन' },
      { name: 'kokrajhar', hindi: 'कोकराझार' },
      { name: 'lakhimpur', hindi: 'लखीमपुर' },
      { name: 'marigaon', hindi: 'मरिगांव' },
      { name: 'nagaon', hindi: 'नगांव' },
      { name: 'nalbari', hindi: 'नलबाड़ी' },
      { name: 'sivasagar', hindi: 'शिवसागर' },
      { name: 'sonitpur', hindi: 'सोनितपुर' },
      { name: 'tinsukia', hindi: 'तिनसुकिया' },
      { name: 'udalguri', hindi: 'उदलगुड़ी' },
      { name: 'west karbi anglong', hindi: 'पश्चिमी कार्बी आंगलोंग' },
      { name: 'baksa', hindi: 'बक्सा' },
      { name: 'biswanath', hindi: 'बिश्वनाथ' },
      { name: 'charaideo', hindi: 'चराइदो' },
      { name: 'hojai', hindi: 'होजाई' },
      { name: 'majuli', hindi: 'माजुली' },
      { name: 'south salmara-mankachar', hindi: 'दक्षिण सालमारा-मनकाचर' },
      { name: 'tamulpur', hindi: 'तमुलपुर' },
      { name: 'kamrup', hindi: 'कामरूप' },
      { name: 'udalguri', hindi: 'उदलगुड़ी' },
      { name: 'dima hasao', hindi: 'दीमा हसाओ' },
    ],
  },
  // ── Chhattisgarh (33 districts) ──
  {
    state: 'chhattisgarh',
    stateCode: 'CG',
    districts: [
      { name: 'bastar', hindi: 'बस्तर' },
      { name: 'bilaspur', hindi: 'बिलासपुर' },
      { name: 'dantewada', hindi: 'दंतेवाड़ा' },
      { name: 'durg', hindi: 'दुर्ग' },
      { name: 'jagdalpur', hindi: 'जगदलपुर' },
      { name: 'janjgir-champa', hindi: 'जांजगीर-चांपा' },
      { name: 'jashpur', hindi: 'जशपुर' },
      { name: 'kabirdham', hindi: 'कबीरधाम' },
      { name: 'korba', hindi: 'कोरबा' },
      { name: 'korea', hindi: 'कोरिया' },
      { name: 'mahasamund', hindi: 'महासमुंद' },
      { name: 'raipur', hindi: 'रायपुर' },
      { name: 'rajanandgaon', hindi: 'राजनांदगांव' },
      { name: 'surguja', hindi: 'सरगुजा' },
      { name: 'bijapur', hindi: 'बीजापुर' },
      { name: 'gariaband', hindi: 'गरियाबंद' },
      { name: 'baloda bazar', hindi: 'बलौदा बाजार' },
      { name: 'bemetara', hindi: 'बेमेतरा' },
      { name: 'mungeli', hindi: 'मुंगेली' },
      { name: 'nandurbar', hindi: 'नांदुरबार' },
      { name: 'surajpur', hindi: 'सूरजपुर' },
      { name: 'balrampur', hindi: 'बलरामपुर' },
      { name: 'gaurela-pendra-marwahi', hindi: 'गौरेला-पेंड्रा-मरवाही' },
      { name: 'khairagarh-chhuikhadan-gandai', hindi: 'खैरागढ़-छुईखदान-गंडाई' },
      { name: 'manendragarh-chirmiri-bharatpur', hindi: 'मनेंद्रगढ़-चिरमिरी-भरतपुर' },
      { name: 'sakti', hindi: 'सक्ति' },
      { name: 'sarangarh-bilaigarh', hindi: 'सारंगढ़-बिलाईगढ़' },
      { name: 'khunti', hindi: 'खूंटी' },
      { name: 'lohardaga', hindi: 'लोहरदगा' },
      { name: 'palamu', hindi: 'पलामू' },
      { name: 'simdega', hindi: 'सिमडेगा' },
      { name: 'latehar', hindi: 'लातेहार' },
      { name: 'garhwa', hindi: 'गढ़वा' },
    ],
  },
  // ── Goa (2 districts) ──
  {
    state: 'goa',
    stateCode: 'GA',
    districts: [
      { name: 'north goa', hindi: 'उत्तर गोवा' },
      { name: 'south goa', hindi: 'दक्षिण गोवा' },
    ],
  },
  // ── Gujarat (33 districts) ──
  {
    state: 'gujarat',
    stateCode: 'GJ',
    districts: [
      { name: 'ahmedabad', hindi: 'अहमदाबाद' },
      { name: 'amreli', hindi: 'अमरेली' },
      { name: 'anand', hindi: 'आनंद' },
      { name: 'banaskantha', hindi: 'बनासकांठा' },
      { name: 'bharuch', hindi: 'भरूच' },
      { name: 'bhavnagar', hindi: 'भावनगर' },
      { name: 'dahod', hindi: 'दाहोद' },
      { name: 'gandhinagar', hindi: 'गांधीनगर' },
      { name: 'jamnagar', hindi: 'जामनगर' },
      { name: 'junagadh', hindi: 'जूनागढ़' },
      { name: 'kachchh', hindi: 'कच्छ' },
      { name: 'kheda', hindi: 'खेड़ा' },
      { name: 'mahesana', hindi: 'महेसाणा' },
      { name: 'narmada', hindi: 'नर्मदा' },
      { name: 'navsari', hindi: 'नवसारी' },
      { name: 'panchmahal', hindi: 'पंचमहल' },
      { name: 'patan', hindi: 'पाटन' },
      { name: 'porbandar', hindi: 'पोरबंदर' },
      { name: 'rajkot', hindi: 'राजकोट' },
      { name: 'sabarkantha', hindi: 'साबरकांठा' },
      { name: 'surat', hindi: 'सूरत' },
      { name: 'surendranagar', hindi: 'सुरेंद्रनगर' },
      { name: 'tapi', hindi: 'तापी' },
      { name: 'vadodara', hindi: 'वडोदरा' },
      { name: 'valsad', hindi: 'वलसाड' },
      { name: 'dang', hindi: 'डांग' },
      { name: 'devbhoomi dwarka', hindi: 'देवभूमि द्वारका' },
      { name: 'gir somnath', hindi: 'गिर सोमनाथ' },
      { name: 'morbi', hindi: 'मोरबी' },
      { name: 'chhota udepur', hindi: 'छोटा उदेपुर' },
      { name: 'aravalli', hindi: 'अरावली' },
      { name: 'mahisagar', hindi: 'महीसागर' },
      { name: 'botad', hindi: 'बोटाद' },
    ],
  },
  // ── Haryana (22 districts) ──
  {
    state: 'haryana',
    stateCode: 'HR',
    districts: [
      { name: 'ambala', hindi: 'अंबाला' },
      { name: 'bhiwani', hindi: 'भिवानी' },
      { name: 'faridabad', hindi: 'फरीदाबाद' },
      { name: 'gurgaon', hindi: 'गुड़गांव' },
      { name: 'hisar', hindi: 'हिसार' },
      { name: 'jhajjar', hindi: 'झज्जर' },
      { name: 'jind', hindi: 'जींद' },
      { name: 'kaithal', hindi: 'कैथल' },
      { name: 'karnal', hindi: 'करनाल' },
      { name: 'kurukshetra', hindi: 'कुरुक्षेत्र' },
      { name: 'mahendragarh', hindi: 'महेंद्रगढ़' },
      { name: 'panipat', hindi: 'पानीपत' },
      { name: 'rewari', hindi: 'रेवाड़ी' },
      { name: 'rohtak', hindi: 'रोहतक' },
      { name: 'sirsa', hindi: 'सिरसा' },
      { name: 'sonipat', hindi: 'सोनीपत' },
      { name: 'yamunanagar', hindi: 'यमुनानगर' },
      { name: 'palwal', hindi: 'पलवल' },
      { name: 'nuh', hindi: 'नूंह' },
      { name: 'charkhi dadri', hindi: 'चरखी दादरी' },
      { name: 'fatehabad', hindi: 'फतेहाबाद' },
      { name: 'pegadapura', hindi: 'पेगाड़ापुरा' },
    ],
  },
  // ── Himachal Pradesh (12 districts) ──
  {
    state: 'himachal pradesh',
    stateCode: 'HP',
    districts: [
      { name: 'bilaspur', hindi: 'बिलासपुर' },
      { name: 'chamba', hindi: 'चंबा' },
      { name: 'hamirpur', hindi: 'हमीरपुर' },
      { name: 'kangra', hindi: 'कांगड़ा' },
      { name: 'kinnaur', hindi: 'किन्नौर' },
      { name: 'kullu', hindi: 'कुल्लू' },
      { name: 'lahaul spiti', hindi: 'लाहौल स्पिति' },
      { name: 'mandi', hindi: 'मंडी' },
      { name: 'shimla', hindi: 'शिमला' },
      { name: 'sirmaur', hindi: 'सिरमौर' },
      { name: 'solan', hindi: 'सोलन' },
      { name: 'una', hindi: 'ऊना' },
    ],
  },
  // ── Jharkhand (24 districts) ──
  {
    state: 'jharkhand',
    stateCode: 'JH',
    districts: [
      { name: 'bokaro', hindi: 'बोकारो' },
      { name: 'chatra', hindi: 'चतरा' },
      { name: 'deoghar', hindi: 'देवघर' },
      { name: 'dhanbad', hindi: 'धनबाद' },
      { name: 'dumka', hindi: 'दुमका' },
      { name: 'east singhbhum', hindi: 'पूर्वी सिंहभूम' },
      { name: 'garhwa', hindi: 'गढ़वा' },
      { name: 'giridih', hindi: 'गिरिडीह' },
      { name: 'godda', hindi: 'गोड्डा' },
      { name: 'gumla', hindi: 'गुमला' },
      { name: 'hazaribag', hindi: 'हजारीबाग' },
      { name: 'jamtara', hindi: 'जामताड़ा' },
      { name: 'khunti', hindi: 'खूंटी' },
      { name: 'koderma', hindi: 'कोडरमा' },
      { name: 'latehar', hindi: 'लातेहार' },
      { name: 'lohardaga', hindi: 'लोहरदगा' },
      { name: 'pakur', hindi: 'पाकुड़' },
      { name: 'palamu', hindi: 'पलामू' },
      { name: 'ranchi', hindi: 'रांची' },
      { name: 'sahibganj', hindi: 'साहिबगंज' },
      { name: 'seraikela-kharsawan', hindi: 'सरायकेला-खरसावां' },
      { name: 'simdega', hindi: 'सिमडेगा' },
      { name: 'west singhbhum', hindi: 'पश्चिमी सिंहभूम' },
      { name: 'ramgarh', hindi: 'रामगढ़' },
    ],
  },
  // ── Karnataka (31 districts) ──
  {
    state: 'karnataka',
    stateCode: 'KA',
    districts: [
      { name: 'bagalkot', hindi: 'बागलकोट' },
      { name: 'bangalore rural', hindi: 'बेंगलुरु ग्रामीण' },
      { name: 'bangalore urban', hindi: 'बेंगलुरु शहरी' },
      { name: 'belgaum', hindi: 'बेलगाम' },
      { name: 'bellary', hindi: 'बल्लारी' },
      { name: 'bidar', hindi: 'बीदर' },
      { name: 'bijapur', hindi: 'बीजापुर' },
      { name: 'chamarajanagar', hindi: 'चामराजनगर' },
      { name: 'chikkaballapur', hindi: 'चिक्कबल्लापुर' },
      { name: 'chikkamagaluru', hindi: 'चिक्कमगलुरु' },
      { name: 'chitradurga', hindi: 'चित्रदुर्ग' },
      { name: 'dakshina kannada', hindi: 'दक्षिण कन्नड़' },
      { name: 'davangere', hindi: 'दावणगेरे' },
      { name: 'dharwad', hindi: 'धारवाड़' },
      { name: 'gadag', hindi: 'गदग' },
      { name: 'hassan', hindi: 'हासन' },
      { name: 'haveri', hindi: 'हावेरी' },
      { name: 'kalaburagi', hindi: 'कलबुरगी' },
      { name: 'kodagu', hindi: 'कोडगू' },
      { name: 'kolar', hindi: 'कोलार' },
      { name: 'koppal', hindi: 'कोप्पल' },
      { name: 'mandya', hindi: 'मांड्या' },
      { name: 'mysore', hindi: 'मैसूर' },
      { name: 'raichur', hindi: 'रायचूर' },
      { name: 'ramanagara', hindi: 'रामनगर' },
      { name: 'shimoga', hindi: 'शिमोगा' },
      { name: 'tumkur', hindi: 'तुमकुर' },
      { name: 'udupi', hindi: 'उडुपी' },
      { name: 'uttara kannada', hindi: 'उत्तर कन्नड़' },
      { name: 'vijayapura', hindi: 'विजयापुर' },
      { name: 'yadgir', hindi: 'यादगीर' },
    ],
  },
  // ── Kerala (14 districts) ──
  {
    state: 'kerala',
    stateCode: 'KL',
    districts: [
      { name: 'alappuzha', hindi: 'अलप्पुझा' },
      { name: 'ernakulam', hindi: 'एर्नाकुलम' },
      { name: 'idukki', hindi: 'इडुक्की' },
      { name: 'kannur', hindi: 'कन्नूर' },
      { name: 'kasaragod', hindi: 'कासरगोड' },
      { name: 'kollam', hindi: 'कोल्लम' },
      { name: 'kottayam', hindi: 'कोट्टायम' },
      { name: 'kozhikode', hindi: 'कोझिकोड' },
      { name: 'malappuram', hindi: 'मलप्पुरम' },
      { name: 'palakkad', hindi: 'पालक्काड' },
      { name: 'pathanamthitta', hindi: 'पथनमथिट्टा' },
      { name: 'thiruvananthapuram', hindi: 'तिरुवनंतपुरम' },
      { name: 'thrissur', hindi: 'त्रिशूर' },
      { name: 'wayanad', hindi: 'वायनाड' },
    ],
  },
  // ── Madhya Pradesh (52 districts) ──
  {
    state: 'madhya pradesh',
    stateCode: 'MP',
    districts: [
      { name: 'balaghat', hindi: 'बालाघाट' },
      { name: 'barwani', hindi: 'बड़वानी' },
      { name: 'betul', hindi: 'बैतूल' },
      { name: 'bhind', hindi: 'भिंड' },
      { name: 'bhopal', hindi: 'भोपाल' },
      { name: 'burhanpur', hindi: 'बुरहानपुर' },
      { name: 'chhatarpur', hindi: 'छतरपुर' },
      { name: 'chhindwara', hindi: 'छिंदवाड़ा' },
      { name: 'damoh', hindi: 'दमोह' },
      { name: 'datia', hindi: 'दतिया' },
      { name: 'dewas', hindi: 'देवास' },
      { name: 'dhar', hindi: 'धार' },
      { name: 'dindori', hindi: 'डिंडोरी' },
      { name: 'guna', hindi: 'गुना' },
      { name: 'gwalior', hindi: 'ग्वालियर' },
      { name: 'harda', hindi: 'हरदा' },
      { name: 'hoshangabad', hindi: 'होशंगाबाद' },
      { name: 'indore', hindi: 'इंदौर' },
      { name: 'jabalpur', hindi: 'जबलपुर' },
      { name: 'jhabua', hindi: 'झाबुआ' },
      { name: 'katni', hindi: 'कटनी' },
      { name: 'khandwa', hindi: 'खंडवा' },
      { name: 'khargone', hindi: 'खरगोन' },
      { name: 'mandla', hindi: 'मंडला' },
      { name: 'mandsaur', hindi: 'मंदसौर' },
      { name: 'morena', hindi: 'मुरैना' },
      { name: 'narsinghpur', hindi: 'नरसिंहपुर' },
      { name: 'neemuch', hindi: 'नीमच' },
      { name: 'panna', hindi: 'पन्ना' },
      { name: 'raisen', hindi: 'रायसेन' },
      { name: 'rajgarh', hindi: 'राजगढ़' },
      { name: 'ratlam', hindi: 'रतलाम' },
      { name: 'rewa', hindi: 'रीवा' },
      { name: 'sagar', hindi: 'सागर' },
      { name: 'satna', hindi: 'सतना' },
      { name: 'sehore', hindi: 'सीहोर' },
      { name: 'seoni', hindi: 'सिवनी' },
      { name: 'shahdol', hindi: 'शहडोल' },
      { name: 'shajapur', hindi: 'शाजापुर' },
      { name: 'shivpuri', hindi: 'शिवपुरी' },
      { name: 'sidhi', hindi: 'सीधी' },
      { name: 'tikamgarh', hindi: 'टीकमगढ़' },
      { name: 'ujjain', hindi: 'उज्जैन' },
      { name: 'umaria', hindi: 'उमरिया' },
      { name: 'vidisha', hindi: 'विदिशा' },
      { name: 'ashoknagar', hindi: 'अशोकनगर' },
      { name: 'sheopur', hindi: 'श्योपुर' },
      { name: 'anuppur', hindi: 'अनूपपुर' },
      { name: 'dindori', hindi: 'डिंडोरी' },
      { name: 'maihar', hindi: 'मैहर' },
      { name: 'nivadi', hindi: 'निवाड़ी' },
      { name: 'pandhurna', hindi: 'पंधुर्ना' },
    ],
  },
  // ── Maharashtra (36 districts) ──
  {
    state: 'maharashtra',
    stateCode: 'MH',
    districts: [
      { name: 'ahmednagar', hindi: 'अहमदनगर' },
      { name: 'akola', hindi: 'अकोला' },
      { name: 'amravati', hindi: 'अमरावती' },
      { name: 'aurangabad', hindi: 'औरंगाबाद' },
      { name: 'beed', hindi: 'बीड' },
      { name: 'bhandara', hindi: 'भंडारा' },
      { name: 'buldhana', hindi: 'बुलढाणा' },
      { name: 'chandrapur', hindi: 'चंद्रपुर' },
      { name: 'dhule', hindi: 'धुले' },
      { name: 'gadchiroli', hindi: 'गडचिरोली' },
      { name: 'gondia', hindi: 'गोंदिया' },
      { name: 'hingoli', hindi: 'हिंगोली' },
      { name: 'jalgaon', hindi: 'जलगांव' },
      { name: 'jalna', hindi: 'जालना' },
      { name: 'kolhapur', hindi: 'कोल्हापुर' },
      { name: 'latur', hindi: 'लातूर' },
      { name: 'mumbai city', hindi: 'मुंबई सिटी' },
      { name: 'mumbai suburban', hindi: 'मुंबई सबर्बन' },
      { name: 'nagpur', hindi: 'नागपुर' },
      { name: 'nanded', hindi: 'नांदेड' },
      { name: 'nandurbar', hindi: 'नंदुरबार' },
      { name: 'nashik', hindi: 'नाशिक' },
      { name: 'osmanabad', hindi: 'उस्मानाबाद' },
      { name: 'palghar', hindi: 'पालघर' },
      { name: 'parbhani', hindi: 'परभणी' },
      { name: 'pune', hindi: 'पुणे' },
      { name: 'raigad', hindi: 'रायगढ़' },
      { name: 'ratnagiri', hindi: 'रत्नागिरी' },
      { name: 'sangli', hindi: 'सांगली' },
      { name: 'satara', hindi: 'सातारा' },
      { name: 'sindhudurg', hindi: 'सिंधुदुर्ग' },
      { name: 'solapur', hindi: 'सोलापुर' },
      { name: 'thane', hindi: 'ठाणे' },
      { name: 'wardha', hindi: 'वर्धा' },
      { name: 'washim', hindi: 'वाशिम' },
      { name: 'yavatmal', hindi: 'यवतमाल' },
    ],
  },
  // ── Manipur (16 districts) ──
  {
    state: 'manipur',
    stateCode: 'MN',
    districts: [
      { name: 'bishnupur', hindi: 'बिश्नुपुर' },
      { name: 'chandel', hindi: 'चंदेल' },
      { name: 'churachandpur', hindi: 'चुराचांदपुर' },
      { name: 'imphal east', hindi: 'इंफाल पूर्व' },
      { name: 'imphal west', hindi: 'इंफाल पश्चिम' },
      { name: 'jiribam', hindi: 'जिरिबाम' },
      { name: 'kakching', hindi: 'काकचिंग' },
      { name: 'kamjong', hindi: 'कामजोंग' },
      { name: 'kangpokpi', hindi: 'कांगपोकपी' },
      { name: 'noney', hindi: 'नोनी' },
      { name: 'pherzawl', hindi: 'फेरज़ौल' },
      { name: 'secured area', hindi: 'सुरक्षित क्षेत्र' },
      { name: 'tamenglong', hindi: 'तमेंगलोंग' },
      { name: 'tengnoupal', hindi: 'तेंगनौपाल' },
      { name: 'thoubal', hindi: 'थौबल' },
      { name: 'ukhrul', hindi: 'उखरूल' },
    ],
  },
  // ── Meghalaya (12 districts) ──
  {
    state: 'meghalaya',
    stateCode: 'ML',
    districts: [
      { name: 'east garo hills', hindi: 'पूर्वी गारो पहाड़ियां' },
      { name: 'east jaintia hills', hindi: 'पूर्वी जैंतिया पहाड़ियां' },
      { name: 'east khasi hills', hindi: 'पूर्वी खासी पहाड़ियां' },
      { name: 'north garo hills', hindi: 'उत्तर गारो पहाड़ियां' },
      { name: 'ri-bhoi', hindi: 'री-भोई' },
      { name: 'south garo hills', hindi: 'दक्षिण गारो पहाड़ियां' },
      { name: 'south west garo hills', hindi: 'दक्षिण पश्चिम गारो पहाड़ियां' },
      { name: 'south west khasi hills', hindi: 'दक्षिण पश्चिम खासी पहाड़ियां' },
      { name: 'west garo hills', hindi: 'पश्चिमी गारो पहाड़ियां' },
      { name: 'west jaintia hills', hindi: 'पश्चिमी जैंतिया पहाड़ियां' },
      { name: 'west khasi hills', hindi: 'पश्चिमी खासी पहाड़ियां' },
      { name: 'south west khasi hills', hindi: 'दक्षिण पश्चिम खासी पहाड़ियां' },
    ],
  },
  // ── Mizoram (11 districts) ──
  {
    state: 'mizoram',
    stateCode: 'MZ',
    districts: [
      { name: 'aizawl', hindi: 'आइज़ोल' },
      { name: 'champhai', hindi: 'चम्फाई' },
      { name: 'kolasib', hindi: 'कोलासिब' },
      { name: 'lawngtlai', hindi: 'लॉंगट्लाई' },
      { name: 'lunglei', hindi: 'लुंगलेई' },
      { name: 'mamit', hindi: 'मामित' },
      { name: 'saiha', hindi: 'साईहा' },
      { name: 'serchhip', hindi: 'सेरछिप' },
      { name: 'hnahthial', hindi: 'ह्नाहथियाल' },
      { name: 'khawzawl', hindi: 'ख्वाज़ौल' },
      { name: 'saitual', hindi: 'साइतुआल' },
    ],
  },
  // ── Nagaland (16 districts) ──
  {
    state: 'nagaland',
    stateCode: 'NL',
    districts: [
      { name: 'dimapur', hindi: 'दीमापुर' },
      { name: 'kohima', hindi: 'कोहिमा' },
      { name: 'mokokchung', hindi: 'मोकोकचुंग' },
      { name: 'mon', hindi: 'मोन' },
      { name: 'peren', hindi: 'पेरेन' },
      { name: 'phek', hindi: 'फेक' },
      { name: 'tuensang', hindi: 'तुएनसांग' },
      { name: 'wokha', hindi: 'वोखा' },
      { name: 'zunheboto', hindi: 'जुन्हेबोटो' },
      { name: 'longleng', hindi: 'लॉंगलेंग' },
      { name: 'noklak', hindi: 'नोकलाक' },
      { name: 'tseminyu', hindi: 'त्सेमिन्यू' },
      { name: 'chumoukedima', hindi: 'चुमौकेदिमा' },
      { name: 'niuland', hindi: 'निउलैंड' },
      { name: 'shamator', hindi: 'शामतोर' },
      { name: 'tirap', hindi: 'तिरप' },
    ],
  },
  // ── Odisha (30 districts) ──
  {
    state: 'odisha',
    stateCode: 'OD',
    districts: [
      { name: 'angul', hindi: 'अनुगुल' },
      { name: 'balangir', hindi: 'बलांगीर' },
      { name: 'balasore', hindi: 'बालासोर' },
      { name: 'bargarh', hindi: 'बरगढ़' },
      { name: 'bhadrak', hindi: 'भद्रक' },
      { name: 'boudh', hindi: 'बौद्ध' },
      { name: 'cuttack', hindi: 'कटक' },
      { name: 'debagarh', hindi: 'देवगढ़' },
      { name: 'dhenkanal', hindi: 'ढेंकनाल' },
      { name: 'gajapati', hindi: 'गजपति' },
      { name: 'ganjam', hindi: 'गंजाम' },
      { name: 'jagatsinghpur', hindi: 'जगतसिंहपुर' },
      { name: 'jajpur', hindi: 'जाजपुर' },
      { name: 'jharsuguda', hindi: 'झारसुगुड़ा' },
      { name: 'kalahandi', hindi: 'कलाहंडी' },
      { name: 'kandhamal', hindi: 'कंधमाल' },
      { name: 'kendrapara', hindi: 'केंद्रपाड़ा' },
      { name: 'keonjhar', hindi: 'केंझर' },
      { name: 'khordha', hindi: 'खोर्धा' },
      { name: 'koraput', hindi: 'कोरापुट' },
      { name: 'malkangiri', hindi: 'मलकानगिरि' },
      { name: 'mayurbhanj', hindi: 'मयूरभंज' },
      { name: 'nabarangapur', hindi: 'नबरंगपुर' },
      { name: 'nayagarh', hindi: 'नयागढ़' },
      { name: 'nuapada', hindi: 'नुआपड़ा' },
      { name: 'puri', hindi: 'पुरी' },
      { name: 'rayagada', hindi: 'रायगड़ा' },
      { name: 'sambalpur', hindi: 'संबलपुर' },
      { name: 'subarnapur', hindi: 'सुबर्णपुर' },
      { name: 'sundergarh', hindi: 'सुंदरगढ़' },
    ],
  },
  // ── Punjab (23 districts) ──
  {
    state: 'punjab',
    stateCode: 'PB',
    districts: [
      { name: 'amritsar', hindi: 'अमृतसर' },
      { name: 'barnala', hindi: 'बरनाला' },
      { name: 'bathinda', hindi: 'बठिंडा' },
      { name: 'faridkot', hindi: 'फरीदकोट' },
      { name: 'fatehgarh sahib', hindi: 'फतेहगढ़ साहिब' },
      { name: 'fazilka', hindi: 'फाजिल्का' },
      { name: 'ferozepur', hindi: 'फिरोज़पुर' },
      { name: 'gurdaspur', hindi: 'गुरदासपुर' },
      { name: 'hoshiarpur', hindi: 'होशियारपुर' },
      { name: 'jalandhar', hindi: 'जलंधर' },
      { name: 'kapurthala', hindi: 'कपूरथला' },
      { name: 'ludhiana', hindi: 'लुधियाना' },
      { name: 'mansa', hindi: 'मानसा' },
      { name: 'moga', hindi: 'मोगा' },
      { name: 'mohali', hindi: 'मोहाली' },
      { name: 'muktsar', hindi: 'मुक्तसर' },
      { name: 'pathankot', hindi: 'पठानकोट' },
      { name: 'patiala', hindi: 'पटियाला' },
      { name: 'rupnagar', hindi: 'रूपनगर' },
      { name: 'sangrur', hindi: 'संगरूर' },
      { name: 'sahibzada ajit singh nagar', hindi: 'साहिबज़ादा अजीत सिंह नगर' },
      { name: 'shaheed bhagat singh nagar', hindi: 'शहीद भगत सिंह नगर' },
      { name: 'tarn taran', hindi: 'तरन तारन' },
    ],
  },
  // ── Rajasthan (42 districts) ──
  {
    state: 'rajasthan',
    stateCode: 'RJ',
    districts: [
      { name: 'ajmer', hindi: 'अजमेर' },
      { name: 'alwar', hindi: 'अलवर' },
      { name: 'banswara', hindi: 'बांसवाड़ा' },
      { name: 'baran', hindi: 'बारां' },
      { name: 'barmer', hindi: 'बाड़मेर' },
      { name: 'bharatpur', hindi: 'भरतपुर' },
      { name: 'bhilwara', hindi: 'भीलवाड़ा' },
      { name: 'bikaner', hindi: 'बीकानेर' },
      { name: 'bundi', hindi: 'बूंदी' },
      { name: 'chittorgarh', hindi: 'चित्तौड़गढ़' },
      { name: 'churu', hindi: 'चूरू' },
      { name: 'dausa', hindi: 'दौसा' },
      { name: 'dholpur', hindi: 'धौलपुर' },
      { name: 'dungarpur', hindi: 'डूंगरपुर' },
      { name: 'jaipur', hindi: 'जयपुर' },
      { name: 'jaisalmer', hindi: 'जैसलमेर' },
      { name: 'jalore', hindi: 'जालौर' },
      { name: 'jhalawar', hindi: 'झालावाड़' },
      { name: 'jhunjhunu', hindi: 'झुंझुनूं' },
      { name: 'jodhpur', hindi: 'जोधपुर' },
      { name: 'karauli', hindi: 'करौली' },
      { name: 'kota', hindi: 'कोटा' },
      { name: 'nagaur', hindi: 'नागौर' },
      { name: 'pali', hindi: 'पाली' },
      { name: 'pratapgarh', hindi: 'प्रतापगढ़' },
      { name: 'rajsamand', hindi: 'राजसमंद' },
      { name: 'sawai madhopur', hindi: 'सवाई माधोपुर' },
      { name: 'sikar', hindi: 'सीकर' },
      { name: 'sirohi', hindi: 'सिरोही' },
      { name: 'tonk', hindi: 'टोंक' },
      { name: 'udaipur', hindi: 'उदयपुर' },
      { name: 'ganganagar', hindi: 'गंगानगर' },
      { name: 'hanumangarh', hindi: 'हनुमानगढ़' },
      { name: 'karauli', hindi: 'करौली' },
      { name: 'udaipur', hindi: 'उदयपुर' },
      { name: 'balotra', hindi: 'बालोतरा' },
      { name: 'beawar', hindi: 'ब्यावर' },
      { name: 'degana', hindi: 'देगाना' },
      { name: 'khetri', hindi: 'खेत्री' },
      { name: 'kushalgarh', hindi: 'कुशलगढ़' },
      { name: 'ladnun', hindi: 'लाडनूं' },
      { name: 'sujangarh', hindi: 'सुजानगढ़' },
    ],
  },
  // ── Sikkim (6 districts) ──
  {
    state: 'sikkim',
    stateCode: 'SK',
    districts: [
      { name: 'east sikkim', hindi: 'पूर्वी सिक्किम' },
      { name: 'north sikkim', hindi: 'उत्तर सिक्किम' },
      { name: 'south sikkim', hindi: 'दक्षिण सिक्किम' },
      { name: 'west sikkim', hindi: 'पश्चिमी सिक्किम' },
      { name: 'gyalshing', hindi: 'ग्यालशिंग' },
      { name: 'soreng', hindi: 'सोरेंग' },
    ],
  },
  // ── Tamil Nadu (38 districts) ──
  {
    state: 'tamil nadu',
    stateCode: 'TN',
    districts: [
      { name: 'ariyalur', hindi: 'अरियालुर' },
      { name: 'chengalpattu', hindi: 'चेंगलपट्टू' },
      { name: 'chennai', hindi: 'चेन्नई' },
      { name: 'coimbatore', hindi: 'कोयंबतूर' },
      { name: 'cuddalore', hindi: 'कुड्डालोर' },
      { name: 'dharmapuri', hindi: 'धर्मपुरी' },
      { name: 'dindigul', hindi: 'दिंडीगुल' },
      { name: 'erode', hindi: 'एरोड' },
      { name: 'kallakurichi', hindi: 'कल्लकुरिची' },
      { name: 'kanchipuram', hindi: 'कांचीपुरम' },
      { name: 'kanyakumari', hindi: 'कन्याकुमारी' },
      { name: 'karur', hindi: 'करूर' },
      { name: 'krishnagiri', hindi: 'कृष्णगिरी' },
      { name: 'madurai', hindi: 'मदुरै' },
      { name: 'mayiladuthurai', hindi: 'मायिलादुतुरै' },
      { name: 'nagapattinam', hindi: 'नागपट्टिनम' },
      { name: 'namakkal', hindi: 'नमक्कल' },
      { name: 'nilgiris', hindi: 'नीलगिरि' },
      { name: 'perambalur', hindi: 'पेरम्बलुर' },
      { name: 'pudukkottai', hindi: 'पुदुक्कोट्टै' },
      { name: 'ramanathapuram', hindi: 'रामनाथपुरम' },
      { name: 'ranipet', hindi: 'रानीपेट' },
      { name: 'salem', hindi: 'सलेम' },
      { name: 'sivaganga', hindi: 'शिवगंगा' },
      { name: 'tenkasi', hindi: 'तेनकासी' },
      { name: 'thanjavur', hindi: 'तंजावुर' },
      { name: 'theni', hindi: 'तेनी' },
      { name: 'thoothukudi', hindi: 'तूतुकुडी' },
      { name: 'tiruchirappalli', hindi: 'तिरुचिरापल्ली' },
      { name: 'tirunelveli', hindi: 'तिरुनेलवेली' },
      { name: 'tirupattur', hindi: 'तिरुपत्तूर' },
      { name: 'tiruvallur', hindi: 'तिरुवल्लूर' },
      { name: 'tiruvannamalai', hindi: 'तिरुवन्नामलाई' },
      { name: 'tiruvarur', hindi: 'तिरुवारूर' },
      { name: 'vellore', hindi: 'वेल्लोर' },
      { name: 'viluppuram', hindi: 'विल्लुपुरम' },
      { name: 'virudhunagar', hindi: 'विरुधुनगर' },
      { name: 'chengalpattu', hindi: 'चेंगलपट्टू' },
    ],
  },
  // ── Telangana (33 districts) ──
  {
    state: 'telangana',
    stateCode: 'TG',
    districts: [
      { name: 'adilabad', hindi: 'आदिलाबाद' },
      { name: 'mancherial', hindi: 'मंचेरियल' },
      { name: 'nirmal', hindi: 'निर्मल' },
      { name: 'nizamabad', hindi: 'निजामाबाद' },
      { name: 'jagitial', hindi: 'जगित्याल' },
      { name: 'peddapalli', hindi: 'पेद्दपल्ली' },
      { name: 'kamareddy', hindi: 'कामारेड्डी' },
      { name: 'rajanna-sircilla', hindi: 'राजन्ना-सिरसिल्ला' },
      { name: 'jayashankar bhupalpally', hindi: 'जयशंकर भूपालपल्ली' },
      { name: 'siddipet', hindi: 'सिद्दिपेट' },
      { name: 'medak', hindi: 'मेदक' },
      { name: 'sangareddy', hindi: 'संगारेड्डी' },
      { name: 'ranga reddy', hindi: 'रंगा रेड्डी' },
      { name: 'hyderabad', hindi: 'हैदराबाद' },
      { name: 'mahabubnagar', hindi: 'महबूबनगर' },
      { name: 'nalgonda', hindi: 'नलगोंडा' },
      { name: 'warangal', hindi: 'वारंगल' },
      { name: 'khammam', hindi: 'खम्मम' },
      { name: 'nagarkurnool', hindi: 'नागरकर्नूल' },
      { name: 'wanaparthy', hindi: 'वानापर्थी' },
      { name: 'jogulamba gadwal', hindi: 'जोगुलम्बा गदवाल' },
      { name: 'nagarkurnool', hindi: 'नागरकर्नूल' },
      { name: 'suryapet', hindi: 'सूर्यापेट' },
      { name: 'mahabubabad', hindi: 'महबूबाबाद' },
      { name: 'jangaon', hindi: 'जंगांव' },
      { name: 'hanamkonda', hindi: 'हनमकोंडा' },
      { name: 'mulugu', hindi: 'मुलुगु' },
      { name: 'bhupalpally', hindi: 'भूपालपल्ली' },
      { name: 'badadchitram', hindi: 'बादादचित्रम' },
      { name: 'kamareddy', hindi: 'कामारेड्डी' },
      { name: 'yadadri bhuvanagiri', hindi: 'यादाद्री भुवनगिरि' },
      { name: 'medchal-malkajgiri', hindi: 'मेडचल-मल्काजगिरि' },
      { name: 'vikarabad', hindi: 'विकाराबाद' },
    ],
  },
  // ── Tripura (8 districts) ──
  {
    state: 'tripura',
    stateCode: 'TR',
    districts: [
      { name: 'dhalai', hindi: 'धलाई' },
      { name: 'gomati', hindi: 'गोमती' },
      { name: 'khowai', hindi: 'खोवाई' },
      { name: 'north tripura', hindi: 'उत्तर त्रिपुरा' },
      { name: 'sepahijala', hindi: 'सिपाहीजला' },
      { name: 'south tripura', hindi: 'दक्षिण त्रिपुरा' },
      { name: 'unakoti', hindi: 'उनाकोटी' },
      { name: 'west tripura', hindi: 'पश्चिमी त्रिपुरा' },
    ],
  },
  // ── Uttar Pradesh (75 districts) ──
  {
    state: 'uttar pradesh',
    stateCode: 'UP',
    districts: [
      { name: 'agra', hindi: 'आगरा' },
      { name: 'aligarh', hindi: 'अलीगढ़' },
      { name: 'allahabad', hindi: 'इलाहाबाद' },
      { name: 'ambedkar nagar', hindi: 'अम्बेडकर नगर' },
      { name: 'amethi', hindi: 'अमेठी' },
      { name: 'amroha', hindi: 'अमरोहा' },
      { name: 'auraiya', hindi: 'औरैया' },
      { name: 'azamgarh', hindi: 'आज़मगढ़' },
      { name: 'baghpat', hindi: 'बागपत' },
      { name: 'bahraich', hindi: 'बहराइच' },
      { name: 'ballia', hindi: 'बलिया' },
      { name: 'balrampur', hindi: 'बलरामपुर' },
      { name: 'banda', hindi: 'बांदा' },
      { name: 'barabanki', hindi: 'बाराबंकी' },
      { name: 'bareilly', hindi: 'बरेली' },
      { name: 'basti', hindi: 'बस्ती' },
      { name: 'bhadohi', hindi: 'भदोही' },
      { name: 'bijnaur', hindi: 'बिजनौर' },
      { name: 'budaun', hindi: 'बदायूं' },
      { name: 'bulandshahr', hindi: 'बुलंदशहर' },
      { name: 'chitrakoot', hindi: 'चित्रकूट' },
      { name: 'deoria', hindi: 'देवरिया' },
      { name: 'etah', hindi: 'एटा' },
      { name: 'etawah', hindi: 'इटावा' },
      { name: 'faizabad', hindi: 'फैजाबाद' },
      { name: 'farrukhabad', hindi: 'फर्रुखाबाद' },
      { name: 'fatehpur', hindi: 'फतेहपुर' },
      { name: 'firozabad', hindi: 'फिरोजाबाद' },
      { name: 'gautam buddha nagar', hindi: 'गौतम बुद्ध नगर' },
      { name: 'ghaziabad', hindi: 'गाजियाबाद' },
      { name: 'ghazipur', hindi: 'गाजीपुर' },
      { name: 'gonda', hindi: 'गोंडा' },
      { name: 'gorakhpur', hindi: 'गोरखपुर' },
      { name: 'hamirpur', hindi: 'हमीरपुर' },
      { name: 'hapur', hindi: 'हापुड़' },
      { name: 'hardoi', hindi: 'हरदोई' },
      { name: 'hathras', hindi: 'हाथरस' },
      { name: 'jalaun', hindi: 'जालौन' },
      { name: 'jaunpur', hindi: 'जौनपुर' },
      { name: 'jhansi', hindi: 'झांसी' },
      { name: 'kannauj', hindi: 'कन्नौज' },
      { name: 'kanpur dehat', hindi: 'कानपुर देहात' },
      { name: 'kanpur nagar', hindi: 'कानपुर नगर' },
      { name: 'kasganj', hindi: 'कासगंज' },
      { name: 'kaushambi', hindi: 'कौशांबी' },
      { name: 'kushinagar', hindi: 'कुशीनगर' },
      { name: 'lakhimpur kheri', hindi: 'लखीमपुर खीरी' },
      { name: 'lalitpur', hindi: 'ललितपुर' },
      { name: 'lucknow', hindi: 'लखनऊ' },
      { name: 'maharajganj', hindi: 'महाराजगंज' },
      { name: 'mahoba', hindi: 'महोबा' },
      { name: 'mainpuri', hindi: 'मैनपुरी' },
      { name: 'mathura', hindi: 'मथुरा' },
      { name: 'mau', hindi: 'मऊ' },
      { name: 'meerut', hindi: 'मेरठ' },
      { name: 'mirzapur', hindi: 'मिर्जापुर' },
      { name: 'moradabad', hindi: 'मुरादाबाद' },
      { name: 'muzaffarnagar', hindi: 'मुजफ्फरनगर' },
      { name: 'pilibhit', hindi: 'पीलीभीत' },
      { name: 'pratapgarh', hindi: 'प्रतापगढ़' },
      { name: 'rae bareli', hindi: 'रायबरेली' },
      { name: 'rampur', hindi: 'रामपुर' },
      { name: 'saharanpur', hindi: 'सहारनपुर' },
      { name: 'sambhal', hindi: 'संभल' },
      { name: 'sant kabir nagar', hindi: 'संत कबीर नगर' },
      { name: 'shahjahanpur', hindi: 'शाहजहांपुर' },
      { name: 'shamli', hindi: 'शामली' },
      { name: 'shravasti', hindi: 'श्रावस्ती' },
      { name: 'siddharthnagar', hindi: 'सिद्धार्थनगर' },
      { name: 'sitapur', hindi: 'सीतापुर' },
      { name: 'sonbhadra', hindi: 'सोनभद्र' },
      { name: 'sultanpur', hindi: 'सुल्तानपुर' },
      { name: 'unnao', hindi: 'उन्नाव' },
      { name: 'varanasi', hindi: 'वाराणसी' },
      { name: 'ayodhya', hindi: 'अयोध्या' },
    ],
  },
  // ── Uttarakhand (13 districts) ──
  {
    state: 'uttarakhand',
    stateCode: 'UK',
    districts: [
      { name: 'almora', hindi: 'अल्मोड़ा' },
      { name: 'bageshwar', hindi: 'बागेश्वर' },
      { name: 'chamoli', hindi: 'चमोली' },
      { name: 'champawat', hindi: 'चम्पावत' },
      { name: 'dehradun', hindi: 'देहरादून' },
      { name: 'haridwar', hindi: 'हरिद्वार' },
      { name: 'nainital', hindi: 'नैनीताल' },
      { name: 'pauri garhwal', hindi: 'पौड़ी गढ़वाल' },
      { name: 'pithoragarh', hindi: 'पिथौरागढ़' },
      { name: 'rudraprayag', hindi: 'रुद्रप्रयाग' },
      { name: 'tehri garhwal', hindi: 'तेहरी गढ़वाल' },
      { name: 'udham singh nagar', hindi: 'उधम सिंह नगर' },
      { name: 'uttarkashi', hindi: 'उत्तरकाशी' },
    ],
  },
  // ── West Bengal (23 districts) ──
  {
    state: 'west bengal',
    stateCode: 'WB',
    districts: [
      { name: 'bankura', hindi: 'बांकुड़ा' },
      { name: 'birbhum', hindi: 'बीरभूम' },
      { name: 'birbhum', hindi: 'बीरभूम' },
      { name: 'dakshin dinajpur', hindi: 'दक्षिण दिनाजपुर' },
      { name: 'darjeeling', hindi: 'दार्जिलिंग' },
      { name: 'hooghly', hindi: 'हुगली' },
      { name: 'howrah', hindi: 'हावड़ा' },
      { name: 'jalpaiguri', hindi: 'जलपाईगुड़ी' },
      { name: 'calcutta', hindi: 'कलकत्ता' },
      { name: 'malda', hindi: 'मालदा' },
      { name: 'murshidabad', hindi: 'मुर्शिदाबाद' },
      { name: 'nadia', hindi: 'नदिया' },
      { name: 'north 24 parganas', hindi: 'उत्तर 24 परगना' },
      { name: 'paschim medinipur', hindi: 'पश्चिम मेदिनीपुर' },
      { name: 'purba medinipur', hindi: 'पूर्व मेदिनीपुर' },
      { name: 'purulia', hindi: 'पुरुलिया' },
      { name: 'south 24 parganas', hindi: 'दक्षिण 24 परगना' },
      { name: 'uttar dinajpur', hindi: 'उत्तर दिनाजपुर' },
      { name: 'asansol', hindi: 'आसनसोल' },
      { name: 'burdwan', hindi: 'बर्धमान' },
      { name: 'kolkata', hindi: 'कोलकाता' },
      { name: 'siliguri', hindi: 'सिलीगुड़ी' },
      { name: 'sundarbans', hindi: 'सुंदरवन' },
    ],
  },
  // ── Union Territories ──
  {
    state: 'andaman and nicobar islands',
    stateCode: 'AN',
    districts: [
      { name: 'nicobar', hindi: 'निकोबार' },
      { name: 'north and middle andaman', hindi: 'उत्तर और मध्य अंडमान' },
      { name: 'south andaman', hindi: 'दक्षिण अंडमान' },
    ],
  },
  {
    state: 'chandigarh',
    stateCode: 'CH',
    districts: [
      { name: 'chandigarh', hindi: 'चंडीगढ़' },
    ],
  },
  {
    state: 'dadra and nagar haveli and daman and diu',
    stateCode: 'DD',
    districts: [
      { name: 'dadra and nagar haveli', hindi: 'दादरा और नगर हवेली' },
      { name: 'daman', hindi: 'दमन' },
      { name: 'diu', hindi: 'दीव' },
    ],
  },
  {
    state: 'jammu and kashmir',
    stateCode: 'JK',
    districts: [
      { name: 'anantnag', hindi: 'अनंतनाग' },
      { name: 'bandipora', hindi: 'बांदीपोरा' },
      { name: 'baramulla', hindi: 'बारामुला' },
      { name: 'budgam', hindi: 'बडगाम' },
      { name: 'doda', hindi: 'डोडा' },
      { name: 'ganderbal', hindi: 'गांदरबल' },
      { name: 'kishtwar', hindi: 'किश्तवाड़' },
      { name: 'kulgam', hindi: 'कुलगाम' },
      { name: 'pulwama', hindi: 'पुलवामा' },
      { name: 'rajouri', hindi: 'राजौरी' },
      { name: 'ramban', hindi: 'रामबन' },
      { name: 'reasi', hindi: 'रियासी' },
      { name: 'samba', hindi: 'सांबा' },
      { name: 'shopian', hindi: 'शोपियां' },
      { name: 'srinagar', hindi: 'श्रीनगर' },
      { name: 'udhampur', hindi: 'उधमपुर' },
    ],
  },
  {
    state: 'ladakh',
    stateCode: 'LA',
    districts: [
      { name: 'leh', hindi: 'लेह' },
      { name: 'kargil', hindi: 'कारगिल' },
    ],
  },
  {
    state: 'lakshadweep',
    stateCode: 'LD',
    districts: [
      { name: 'lakshadweep', hindi: 'लक्षद्वीप' },
    ],
  },
  {
    state: 'delhi',
    stateCode: 'DL',
    districts: [
      { name: 'central delhi', hindi: 'केंद्रीय दिल्ली' },
      { name: 'east delhi', hindi: 'पूर्वी दिल्ली' },
      { name: 'new delhi', hindi: 'नई दिल्ली' },
      { name: 'north delhi', hindi: 'उत्तर दिल्ली' },
      { name: 'north east delhi', hindi: 'उत्तर पूर्वी दिल्ली' },
      { name: 'north west delhi', hindi: 'उत्तर पश्चिमी दिल्ली' },
      { name: 'shahdara', hindi: 'शाहदरा' },
      { name: 'south delhi', hindi: 'दक्षिण दिल्ली' },
      { name: 'south east delhi', hindi: 'दक्षिण पूर्वी दिल्ली' },
      { name: 'south west delhi', hindi: 'दक्षिण पश्चिमी दिल्ली' },
      { name: 'west delhi', hindi: 'पश्चिमी दिल्ली' },
    ],
  },
  {
    state: 'puducherry',
    stateCode: 'PY',
    districts: [
      { name: 'karaikal', hindi: 'कराईकल' },
      { name: 'mahe', hindi: 'माहे' },
      { name: 'puducherry', hindi: 'पुडुचेरी' },
      { name: 'yanam', hindi: 'यानम' },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════
// Bihar-Specific Keywords (political figures, institutions)
// ═══════════════════════════════════════════════════════════════════

export const BIHAR_KEYWORDS: string[] = [
  'bihar',
  'nitish kumar',
  'nitish',
  'samrat choudhary',
  'samrat',
  'tejashwi',
  'tejashwi yadav',
  'chirag paswan',
  'chirag',
  'jitan ram manjhi',
  'upendra kushwaha',
  'bpsc',
  'bseb',
  'patna high court',
  'bihar police',
  'vidhan sabha',
  'बिहार विधानसभा',
  'बिहार सरकार',
  'बिहार पुलिस',
  'बिहार लोक सेवा आयोग',
  'बिहार शरीफ',
  'पटना',
  'पाटलिपुत्र',
];

// ═══════════════════════════════════════════════════════════════════
// All Indian States and UTs (for state-level matching)
// ═══════════════════════════════════════════════════════════════════

export const ALL_STATES_AND_UTS: string[] = [
  // States
  'andhra pradesh', 'arunachal pradesh', 'assam', 'bihar', 'chhattisgarh',
  'goa', 'gujarat', 'haryana', 'himachal pradesh', 'jharkhand',
  'karnataka', 'kerala', 'madhya pradesh', 'maharashtra', 'manipur',
  'meghalaya', 'mizoram', 'nagaland', 'odisha', 'punjab',
  'rajasthan', 'sikkim', 'tamil nadu', 'telangana', 'tripura',
  'uttar pradesh', 'uttarakhand', 'west bengal',
  // Union Territories
  'andaman and nicobar islands', 'chandigarh',
  'dadra and nagar haveli and daman and diu', 'delhi',
  'jammu and kashmir', 'ladakh', 'lakshadweep', 'puducherry',
  // Hindi equivalents
  'आंध्र प्रदेश', 'अरुणाचल प्रदेश', 'असम', 'बिहार', 'छत्तीसगढ़',
  'गोवा', 'गुजरात', 'हरियाणा', 'हिमाचल प्रदेश', 'झारखंड',
  'कर्नाटक', 'केरल', 'मध्य प्रदेश', 'महाराष्ट्र', 'मणिपुर',
  'मेघालय', 'मिज़ोरम', 'नागालैंड', 'ओडिशा', 'पंजाब',
  'राजस्थान', 'सिक्किम', 'तमिल नाडु', 'तेलंगाना', 'त्रिपुरा',
  'उत्तर प्रदेश', 'उत्तराखंड', 'पश्चिम बंगाल',
  // UTs in Hindi
  'अंडमान और निकोबार', 'चंडीगढ़',
  'दादरा और नगर हवेली और दमन और दीव', 'दिल्ली',
  'जम्मू और कश्मीर', 'लद्दाख', 'लक्षद्वीप', 'पुडुचेरी',
];

// ═══════════════════════════════════════════════════════════════════
// Pre-built flat lookup maps for fast matching
// ═══════════════════════════════════════════════════════════════════

// Bihar district names (English, lowercase)
export const BIHAR_DISTRICT_NAMES: string[] = BIHAR_DISTRICTS.map(d => d.name);

// Bihar district names (Hindi)
export const BIHAR_DISTRICT_HINDI: string[] = BIHAR_DISTRICTS.map(d => d.hindi);

// All non-Bihar district names (English, lowercase)
export const NON_BIHAR_DISTRICT_NAMES: string[] = ALL_INDIA_STATES
  .filter(s => s.stateCode !== 'BR')
  .flatMap(s => s.districts.map(d => d.name));

// All non-Bihar district names (Hindi)
export const NON_BIHAR_DISTRICT_HINDI: string[] = ALL_INDIA_STATES
  .filter(s => s.stateCode !== 'BR')
  .flatMap(s => s.districts.map(d => d.hindi));

// All state/UT names (English, lowercase) — excluding Bihar
export const NON_BIHAR_STATE_NAMES: string[] = ALL_STATES_AND_UTS
  .filter(s => s !== 'bihar' && s !== 'बिहार');

// Combined Bihar terms (districts + keywords + infra)
export const ALL_BIHAR_TERMS: string[] = [
  ...BIHAR_DISTRICT_NAMES,
  ...BIHAR_DISTRICT_HINDI,
  ...BIHAR_KEYWORDS,
  ...BIHAR_INFRA_KEYWORDS,
];

// Combined non-Bihar terms (districts + states)
export const ALL_NON_BIHAR_GEO_TERMS: string[] = [
  ...NON_BIHAR_DISTRICT_NAMES,
  ...NON_BIHAR_DISTRICT_HINDI,
  ...NON_BIHAR_STATE_NAMES,
];
